version : '2'

services:
  goo:
    image : avezila/goo
    environment:
      - PORT=80
    links :
      - goo-mongo
  goo-mongo:
    image : avezila/goo-mongo
    volumes :
      - ./runtime/mongo:/data
  goo-web:
    image : avezila/goo-web
    environment:
      - SERVER=http://docker
      - PORT=80
  goo-nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - goo
      - goo-web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
