version : '2'

services:
  goo:
    image : avezila/goo
    environment:
      - PORT=5354
    links :
      - goo-mongo
  goo-mongo:
    image : avezila/goo-mongo
    volumes :
      - ./runtime/mongo:/data
  goo-web:
    image : avezila/goo-web
    environment:
      - SERVER=https://goo.avezila.com
      - PORT=3000
  goo-nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - goo
      - goo-web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /ssl/avezila.com/:/ssl/
