version : '2'

services:
  goo:
    image : avezila/goo
    environment:
      - PORT=80
    links :
      - goo-mongo
  goo-mongo:
    image : avezila/goo-mongo
    volumes :
      - ./runtime/mongo:/data
  goo-web:
    image : avezila/goo-web
    environment:
      - SERVER=https://goo.avezila.com
      - PORT=80
  goo-nginx:
    image: avezila/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - goo
      - goo-web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./runtime/nginx:/usr/share/nginx/html
